name: Helm Deploy Test

on:
  workflow_dispatch:

jobs:
  helm-deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies and run tests
        working-directory: ./python
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          python tests.py -v

      - name: Set up kind cluster
        uses: helm/kind-action@v1.9.0
        with:
            cluster_name: kind

      - name: Build Docker image
        run: |
          docker build -t tyk-sre-assignment:latest .

      - name: Load image into kind
        run: |
          kind load docker-image tyk-sre-assignment:latest

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy via Helm
        run: |
          helm install tyk-sre ./helm/tyk-sre -n ci --create-namespace
          kubectl get pods -n ci
          kubectl rollout status deployment/tyk-sre-deployment -n ci --timeout=120s

      # Testing /healthz from inside the cluster
      - name: Test /healthz via curl pod
        run: |
          kubectl run curl-healthz --image=curlimages/curl -n ci --restart=Never --rm -i -- \
            curl -sS -f http://tyk-sre-service:8080/healthz

      # Testing /health/apiserver from inside the cluster
      - name: Test /health/apiserver via curl pod
        run: |
          kubectl run curl-apiserver --image=curlimages/curl -n ci --restart=Never --rm -i -- \
            curl -sS -f http://tyk-sre-service:8080/health/apiserver

      # Testing /health/deployments from inside the cluster
      - name: Wait for system deployments to settle
        run: |
            kubectl wait deployment --all --for=condition=Available --timeout=90s -n kube-system || true
            kubectl wait deployment --all --for=condition=Available --timeout=90s -n ci || true

      - name: Test /health/deployments via curl pod
        run: |
            kubectl run curl-deployments --image=curlimages/curl -n ci --restart=Never --rm -i -- \
            curl -sS http://tyk-sre-service:8080/health/deployments

